Status Module functions for Discord Bot
Bungalow-13/Bungalow-13 pull request #541
Opened 2022-02-02 01:07 UTC by Kalesonki

## About The Pull Request

Adds functions required by status cog of the discord bot.

Provides also "Who" and "Adminwho" to the bot.

## Why It's Good For The Game

Provides some more info about status of the server, as well as allowing custom notifications for in game events or bwoinks.

## Changelog
I am too sleepy to do this.

2022-02-02 01:11 UTC, DaddyIssues98 commented on code/controllers/subsystem/redbot.dm
> +	world.Export("http://[bot_ip]/?[list2params(data)]")
oof

2022-02-03 06:37 UTC, BootlegBow approved these changes
looks fine to me

2022-02-03 06:38 UTC, retlaw34 requested changes

2022-02-03 06:38 UTC, retlaw34 commented on code/controllers/subsystem/redbot.dm
> +/datum/controller/subsystem/redbot/proc/send_discord_message(var/channel, var/message, var/priority_type)
```suggestion
/datum/controller/subsystem/redbot/proc/send_discord_message(channel, message, priority_type)
```

2022-02-03 21:39 UTC, merged