BEE ASS NUKE.
Bungalow-13/Bungalow-13 pull request #660
Opened 2022-03-08 00:46 UTC by DaddyIssues98

## About The Pull Request

make bee capable of launching a stinger from they asses.

## Why It's Good For The Game

 unique thing for the race
## Changelog
:cl:
add: adds stinger organ
add:  adds stinger ability to beepeople
del: removed the ability to remove bee abdomens from beepeople
/:cl:

2022-03-08 13:33 UTC, bruhlookatthisdood commented
it returns

2022-03-09 17:48 UTC, bruhlookatthisdood commented
please include the nerf in the changelog thanks

2022-03-22 13:23 UTC, EgorDinamit requested changes
So yeah, it'd be better if the ability was tied to the organ, not to the species.

2022-06-18 04:19 UTC, thevandie commented
isn't this already merged? or are we just on infinite test-merge?

2022-12-18 14:24 UTC, DaddyIssues98 commented
who made this? is shit

2025-04-25 06:59 UTC, closed without merging